add deps for webkitgtk*
care may be needed for pandoc-bin package on aarch64

diff --git a/libs/libyuv/libyuv.SlackBuild b/libs/libyuv/libyuv.SlackBuild
--- a/libs/libyuv/libyuv.SlackBuild
+++ b/libs/libyuv/libyuv.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/bash
-#
-# Slackware build script for webkit2gtk
-#
-# Copyright 2016-2023 Willy Sudiarto Raharjo <willysr@slackbuilds.org>
+
+# Slackware build script for libyuv
+
+# Copyright 2022 Vijay Marcel
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,16 +24,12 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=webkit2gtk
-SRCNAM=webkitgtk
-VERSION=${VERSION:-2.40.1}
+PRGNAM=libyuv
+VERSION=${VERSION:-20220925_84d76f9}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_lngn}
 PKGTYPE=${PKGTYPE:-txz}
-
-TMP=${TMP:-/tmp/lngn}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
+GITNAM=${GITNAM:-84d76f9b4ef15b282b0b62a3d73f7ab1b7f41f7e}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -43,36 +39,45 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
 fi
 
+TMP=${TMP:-/tmp/lngn}
+PKG=$TMP/package-$PRGNAM
+OUTPUT=${OUTPUT:-/tmp}
+
 if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686 -g1"
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686 -g1"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC -g1"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -fPIC -g1"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
 fi
 
-set -eu
+set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $SRCNAM-$VERSION
-tar xvf $CWD/$SRCNAM-$VERSION.tar.xz
-cd $SRCNAM-$VERSION
+rm -rf $PRGNAM-$VERSION
+rm -rf $PRGNAM-$GITNAM
+tar xvf $CWD/$PRGNAM-$GITNAM.tar.gz
+cd $PRGNAM-$GITNAM
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -80,51 +85,29 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# why do we want this?
-#patch -p1 < $CWD/unhide-deprecated-api.patch
-# FIX GCC 13
-patch -p1 < $CWD/0001-Fix-build-of-SourceBrush.cpp.patch
+if [ "$ARCH" = "x86_64" ]; then
+    sed -i 's+DESTINATION lib+DESTINATION lib64+g' $TMP/$PRGNAM-$GITNAM/CMakeLists.txt
+fi
 
-# changed to be more like arch
-mkdir -p build
-cd build
-  cmake -DPORT=GTK \
-	-DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
-	-DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-	-DCMAKE_BUILD_TYPE=Release \
-	-DCMAKE_SKIP_RPATH=ON \
-	-DCMAKE_INSTALL_PREFIX=/usr \
-	-DLIB_INSTALL_DIR=/usr/lib${LIBDIRSUFFIX} \
-	-DLIBEXEC_INSTALL_DIR=/usr/lib${LIBDIRSUFFIX}/webkit2gtk-4.0 \
-	-DENABLE_MINIBROWSER=ON \
-	-DUSE_SOUP2=ON \
-	-DENABLE_JOURNALD_LOG=OFF \
-	-DENABLE_DOCUMENTATION=OFF \
-	-DENABLE_BUBBLEWRAP_SANDBOX=OFF \
-	-DUSE_SYSTEM_MALLOC=ON \
-	-DUSE_AVIF=ON \
-        -Wno-dev \
-        -G Ninja \
-        ..
+cmake -B build -S $TMP/$PRGNAM-$GITNAM \
+    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
+    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
+    -DCMAKE_INSTALL_PREFIX=/usr \
+    -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib${LIBDIRSUFFIX} \
+    -DCMAKE_INSTALL_BINDIR:PATH=/usr/bin \
+    -DBUILD_SHARED_LIBS:BOOL=ON \
+    -DCMAKE_BUILD_TYPE=Release
 
-# The build might crash on high specs machines because ninja eat all
-# of the resources, so let's try to limit it to half the available ones
-"${NINJA:=ninja}" -j$(expr $(nproc) )
-DESTDIR=$PKG $NINJA -j1 install
-
-cd ..
+make -C build
+make -C build install DESTDIR=$PKG
 
 rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-# remove the unneeded binary since all 3 packages create one
-# we just need the libs for epiphany & gnome
-rm -R $PKG/usr/bin
-
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a NEWS $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a AUTHORS DEPS LICENSE OWNERS PATENTS README.md README.chromium docs/* $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
diff --git a/multimedia/svt-av1/svt-av1.SlackBuild b/multimedia/svt-av1/svt-av1.SlackBuild
--- a/multimedia/svt-av1/svt-av1.SlackBuild
+++ b/multimedia/svt-av1/svt-av1.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/bash
-#
-# Slackware build script for webkit2gtk
-#
-# Copyright 2016-2023 Willy Sudiarto Raharjo <willysr@slackbuilds.org>
+
+# Slackware build script for SVT-AV1
+
+# Copyright 2022 Vijay Marcel
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,55 +24,61 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=webkit2gtk
-SRCNAM=webkitgtk
-VERSION=${VERSION:-2.40.1}
+PRGNAM=svt-av1
+VERSION=${VERSION:-1.5.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_lngn}
 PKGTYPE=${PKGTYPE:-txz}
+
+DIR=${DIR:-SVT-AV1-v1.5.0}
+
+if [ -z "$ARCH" ]; then
+  case "$( uname -m )" in
+    i?86) export ARCH=i586 ;;
+    arm*) export ARCH=arm ;;
+       *) export ARCH=$( uname -m ) ;;
+  esac
+fi
 
 TMP=${TMP:-/tmp/lngn}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) ARCH=i586 ;;
-    arm*) ARCH=arm ;;
-       *) ARCH=$( uname -m ) ;;
-  esac
-fi
-
-if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
-  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
-  exit 0
-fi
-
 if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686 -g1"
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686 -fPIC"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686 -g1"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686 -fPIC"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC -g1"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -fPIC -g1"
+  SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
 fi
 
-set -eu
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}"  ]; then
+  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
+  exit 0
+fi
+
+set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $SRCNAM-$VERSION
-tar xvf $CWD/$SRCNAM-$VERSION.tar.xz
-cd $SRCNAM-$VERSION
+rm -rf $DIR
+tar xvf $CWD/$DIR.tar.gz
+cd $DIR
+
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -80,51 +86,28 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# why do we want this?
-#patch -p1 < $CWD/unhide-deprecated-api.patch
-# FIX GCC 13
-patch -p1 < $CWD/0001-Fix-build-of-SourceBrush.cpp.patch
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
 
-# changed to be more like arch
-mkdir -p build
-cd build
-  cmake -DPORT=GTK \
-	-DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
-	-DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-	-DCMAKE_BUILD_TYPE=Release \
-	-DCMAKE_SKIP_RPATH=ON \
-	-DCMAKE_INSTALL_PREFIX=/usr \
-	-DLIB_INSTALL_DIR=/usr/lib${LIBDIRSUFFIX} \
-	-DLIBEXEC_INSTALL_DIR=/usr/lib${LIBDIRSUFFIX}/webkit2gtk-4.0 \
-	-DENABLE_MINIBROWSER=ON \
-	-DUSE_SOUP2=ON \
-	-DENABLE_JOURNALD_LOG=OFF \
-	-DENABLE_DOCUMENTATION=OFF \
-	-DENABLE_BUBBLEWRAP_SANDBOX=OFF \
-	-DUSE_SYSTEM_MALLOC=ON \
-	-DUSE_AVIF=ON \
-        -Wno-dev \
-        -G Ninja \
-        ..
+export LDFLAGS+=' -Wl,-z,noexecstack'
 
-# The build might crash on high specs machines because ninja eat all
-# of the resources, so let's try to limit it to half the available ones
-"${NINJA:=ninja}" -j$(expr $(nproc) )
-DESTDIR=$PKG $NINJA -j1 install
+cmake -B build -S $TMP/$DIR \
+        -DCMAKE_BUILD_TYPE:STRING=None \
+        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
+        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib${LIBDIRSUFFIX} \
+        -Wno-dev
 
-cd ..
+make -C build
+make -C build install DESTDIR=$PKG
 
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" \
+  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+# Don't ship .la files:
 rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-# remove the unneeded binary since all 3 packages create one
-# we just need the libs for epiphany & gnome
-rm -R $PKG/usr/bin
-
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a NEWS $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a CHANGELOG.md PATENTS.md LICENSE.md STYLE.md README.md Docs   $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
