chafa: add opt dep for fastfetch

diff --git a/pkg/chafa/chafa.SlackBuild b/pkg/chafa/chafa.SlackBuild
--- a/pkg/chafa/chafa.SlackBuild
+++ b/pkg/chafa/chafa.SlackBuild
@@ -1,8 +1,9 @@
 #!/bin/bash
 
-# Slackware build script for fastfetch
+# Slackware build script for chafa
 
-# Copyright 2023-2025 Samuel Young, MO, USA
+# Copyright 2022-2025  Vijay Marcel
+
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -22,10 +23,28 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+#---------------------------Changelog-------------------------------------------#
+
+# 20/08/2022: Added to slackbuilds.org
+# 11/05/2023: updated to version 1.12.4
+# 05/12/2023: updated to version  1.12.5
+# During compilation chafa fails to build because of error in libwebp
+# saying error adding symbols: DSO missing from command line
+# to avoid this modify the CFLAGS to CFLAGS="$SLKCFLAGS $(pkg-config --libs libwebp)"
+# Thanks to Christoph Willing for the solution.
+# 05/02/2024: updated to version 1.14.0 libavif is an optional dependency.
+# This slackbuild builds without avif support.
+# 18/08/2024: Updated to version 1.14.2
+# 11/09/2024: Opdated to version 1.14.4
+# 20/11/2024: Updated to version 1.14.5
+# 10/06/2025: updated to version 1.16.1
+# 25/07/2025: updated to version 1.16.2
+#-----------------------------------------------------------------------------------------#
+
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=fastfetch
-VERSION=${VERSION:-2.50.2}
+PRGNAM=chafa
+VERSION=${VERSION:-1.16.2}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_lngn}
 PKGTYPE=${PKGTYPE:-txz}
@@ -48,16 +67,16 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
+  SLKCFLAGS="-O2 -march=i586 -mtune=i686 -pipe"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686 -pipe"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
+  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC -pipe"
   LIBDIRSUFFIX="64"
 elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC"
+  SLKCFLAGS="-O2 -march=armv8-a -mtune=generic -fPIC -pipe"
   LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
@@ -65,70 +84,55 @@ else
 fi
 
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee -a  $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
+tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
 cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-mkdir -p build
-cd build
-  cmake \
-    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
-    -DCMAKE_INSTALL_PREFIX=/usr \
-    -DPACKAGES_DISABLE_AM=ON \
-    -DPACKAGES_DISABLE_APK=ON \
-    -DPACKAGES_DISABLE_CHOCO=ON \
-    -DPACKAGES_DISABLE_DPKG=ON \
-    -DPACKAGES_DISABLE_EMERGE=ON \
-    -DPACKAGES_DISABLE_EOPKG=ON \
-    -DPACKAGES_DISABLE_LINGLONG=ON \
-    -DPACKAGES_DISABLE_LPKG=ON \
-    -DPACKAGES_DISABLE_LPKGBUILD=ON \
-    -DPACKAGES_DISABLE_MACPORTS=ON \
-    -DPACKAGES_DISABLE_OPKG=ON \
-    -DPACKAGES_DISABLE_PACMAN=ON \
-    -DPACKAGES_DISABLE_PACSTALL=ON \
-    -DPACKAGES_DISABLE_PALUDIS=ON \
-    -DPACKAGES_DISABLE_PKG=ON \
-    -DPACKAGES_DISABLE_RPM=ON \
-    -DPACKAGES_DISABLE_SCOOP=ON \
-    -DPACKAGES_DISABLE_SNAP=ON \
-    -DPACKAGES_DISABLE_SORCERY=ON \
-    -DPACKAGES_DISABLE_WINGET=ON \
-    -DPACKAGES_DISABLE_XBPS=ON \
-    -DCMAKE_BUILD_TYPE=Release ..
-  cmake --build .
-  DESTDIR=$PKG cmake --install .
-cd ..
+CPPFLAGS="-D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS" \
+CFLAGS="$SLKCFLAGS $(pkg-config --libs libwebp)" \
+CXXFLAGS="$SLKCFLAGS" \
+./configure \
+  --prefix=/usr \
+  --libdir=/usr/lib${LIBDIRSUFFIX} \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --enable-man \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/$PRGNAM-$VERSION \
+  --enable-shared \
+  --disable-static \
+  --disable-gtk-doc \
+  --disable-gtk-doc-html \
+  --disable-gtk-doc-pdf \
+  --with-gnu-ld \
+  --build=$ARCH-slackware-linux
+
+make
+make install DESTDIR=$PKG
+/sbin/ldconfig
+
+# Don't ship .la files:
+rm -f $PKG/usr/lib${LIBDIRSUFFIX}/*.la
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
-
-rm -r $PKG/usr/share/licenses
-
-mv $PKG/usr/share/man $PKG/usr
+  | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
 
 find $PKG/usr/man -type f -exec gzip -9 {} \;
 for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 
-# Only install fish shell completions if fish is installed
-if [ ! -e /usr/bin/fish ]; then
-  rm -rv $PKG/usr/share/fish
-fi
-
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a \
-  CHANGELOG.md README.md LICENSE \
-  $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a AUTHORS COPYING COPYING.LESSER HACKING NEWS README README.md SECURITY.md  $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
@@ -136,4 +140,4 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/slack-required > $PKG/install/slack-required
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
